# Generated by Django 4.0.5 on 2023-03-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='authorEmail',
            field=models.EmailField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.TextField(default='anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=130, unique=True),
        ),
    ]
